// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using OperacaoFlorestal.Data;

#nullable disable

namespace OperacaoFlorestal.Migrations
{
    [DbContext(typeof(OperacaoFlorestalContext))]
    [Migration("20250831212610_MaquinarioEVooVant")]
    partial class MaquinarioEVooVant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OperacaoFlorestal.Models.Maquinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("datetime(6)");

                    b.Property<Point>("LocalizacaoAtual")
                        .HasColumnType("geometry");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StatusOperacional")
                        .HasColumnType("int");

                    b.Property<string>("TipoMaquinario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Maquinarios");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.VooVant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicoesClimaticas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataFimVoo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicioVoo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEquipe")
                        .HasColumnType("int");

                    b.Property<int>("IdMaquinario")
                        .HasColumnType("int");

                    b.Property<string>("TipoVoo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdMaquinario");

                    b.ToTable("VooVants");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.VooVant", b =>
                {
                    b.HasOne("OperacaoFlorestal.Models.Maquinario", "Maquinario")
                        .WithMany("Voos")
                        .HasForeignKey("IdMaquinario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquinario");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.Maquinario", b =>
                {
                    b.Navigation("Voos");
                });
#pragma warning restore 612, 618
        }
    }
}
