// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using OperacaoFlorestal.Data;

#nullable disable

namespace OperacaoFlorestal.Migrations
{
    [DbContext(typeof(OperacaoFlorestalContext))]
    [Migration("20250901102652_ColetaDeDados")]
    partial class ColetaDeDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OperacaoFlorestal.Models.DadoBrutoMaquinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdMaquinario")
                        .HasColumnType("int");

                    b.Property<int>("MaquinarioId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MaquinarioId");

                    b.ToTable("DadosBrutosMaquinario");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.DadoBrutoVant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdVoo")
                        .HasColumnType("int");

                    b.Property<int>("VooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VooId");

                    b.ToTable("DadosBrutosVant");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.Maquinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<Point>("LocalizacaoAtual")
                        .HasColumnType("geometry");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StatusOperacional")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Maquinarios");

                    b.HasDiscriminator().HasValue("Maquinario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.VooVant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicoesClimaticas")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataFimVoo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicioVoo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEquipe")
                        .HasColumnType("int");

                    b.Property<int>("IdMaquinario")
                        .HasColumnType("int");

                    b.Property<string>("TipoVoo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdMaquinario");

                    b.ToTable("VooVants");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.MaquinarioPesado", b =>
                {
                    b.HasBaseType("OperacaoFlorestal.Models.Maquinario");

                    b.Property<double>("CapacidadeCarga")
                        .HasColumnType("double");

                    b.Property<string>("Combustivel")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("MaquinarioPesado");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.MaquinarioVANT", b =>
                {
                    b.HasBaseType("OperacaoFlorestal.Models.Maquinario");

                    b.Property<int>("TipoDrone")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MaquinarioVANT");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.DadoBrutoMaquinario", b =>
                {
                    b.HasOne("OperacaoFlorestal.Models.Maquinario", "Maquinario")
                        .WithMany()
                        .HasForeignKey("MaquinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquinario");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.DadoBrutoVant", b =>
                {
                    b.HasOne("OperacaoFlorestal.Models.VooVant", "Voo")
                        .WithMany("DadosBrutos")
                        .HasForeignKey("VooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voo");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.VooVant", b =>
                {
                    b.HasOne("OperacaoFlorestal.Models.Maquinario", "Maquinario")
                        .WithMany("Voos")
                        .HasForeignKey("IdMaquinario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquinario");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.Maquinario", b =>
                {
                    b.Navigation("Voos");
                });

            modelBuilder.Entity("OperacaoFlorestal.Models.VooVant", b =>
                {
                    b.Navigation("DadosBrutos");
                });
#pragma warning restore 612, 618
        }
    }
}
